Creating story
DSSD-Madison/Nagoya pull request #68
Opened 2023-04-22 15:15 UTC by PranavC10

2023-05-03 18:10 UTC, GeoffreyXue requested changes

2023-05-05 14:47 UTC, PranavC10 commented on content/topics/sustainable-cities-and-communities/Stories/Pranav-Chandaliya-Comparing_factors.md
> +{{< image class="medium" src="https://raw.githubusercontent.com/DSSD-Madison/Nagoya/story/pranav-chandaliya/content/topics/sustainable-cities-and-communities/Stories/Pranav-Chandaliya-Images/Comparin
Hi @GeoffreyXue ,
I tried replacing image links the way you suggested but for me, the image is not displayed. Please could you look into this issue?

2023-05-05 14:52 UTC, PranavC10 commented
Hi,
@GeoffreyXue I have updated the image path and meta data.

2023-05-07 18:22 UTC, GeoffreyXue reviewed
Everything else looks good, just one last note!

2023-05-07 18:22 UTC, GeoffreyXue commented on content/topics/sustainable-cities-and-communities/Stories/Pranav-Chandaliya-Images/Data-Table.jpg
@PranavC10 Is this image still needed? I noticed you've switched over to using a markdown table instead of this, so just double checking!

2023-05-08 02:03 UTC, PranavC10 commented on content/topics/sustainable-cities-and-communities/Stories/Pranav-Chandaliya-Images/Data-Table.jpg
@GeoffreyXue I have removed the image. Thanks

2023-05-08 16:01 UTC, GeoffreyXue approved these changes
Looks good!

2023-05-08 16:01 UTC, merged