Language inequality
DSSD-Madison/Nagoya pull request #75
Opened 2023-04-29 19:02 UTC by averma1010

2023-05-03 18:11 UTC, GeoffreyXue requested changes

2023-05-15 23:40 UTC, GeoffreyXue reviewed
Everything related to the story looks good! Just two questions on the remaining two images left in the story folder.

The deploy preview has the images too large, but that's a formatting issue on our side of the website

2023-05-15 23:40 UTC, GeoffreyXue commented on content/topics/reduced-inequalities/Stories/Image_folder/saved.jpeg
Is this image still needed? I see it isn't referenced anywhere in the story

2023-05-15 23:40 UTC, GeoffreyXue commented on content/topics/reduced-inequalities/Stories/Image_folder/Literacyrate.jpeg
Same comment, is this needed if it isn't referenced?

2023-05-16 14:55 UTC, PranavC10 commented on content/topics/reduced-inequalities/Stories/Image_folder/saved.jpeg
@averma1010 Hi Akshay Please could you check this.

2023-05-17 02:58 UTC, averma1010 commented on content/topics/reduced-inequalities/Stories/Image_folder/saved.jpeg
Hi,
The map shows the geographic distribution of the non-Spanish speakers.  I think it's important cause it gives you an idea that the states or municipalities that are affected are bordering each other and are not distributed randomly over the country. this coupled with the literacy map and their overlap hints at a systematic limitation or policy failure in these clusters of states.

2023-05-17 03:01 UTC, averma1010 commented on content/topics/reduced-inequalities/Stories/Image_folder/Literacyrate.jpeg
The paragraph below the maps references them in brief

2023-05-17 03:08 UTC, averma1010 commented on content/topics/reduced-inequalities/Stories/Image_folder/saved.jpeg
Oh, my bad. I didn't realize I had multiple map images. I have removed them now.

2023-05-17 03:08 UTC, averma1010 commented on content/topics/reduced-inequalities/Stories/Image_folder/Literacyrate.jpeg
Oh, my bad. I didn't realize I had multiple map images. I have removed them now.

2023-05-17 03:55 UTC, GeoffreyXue approved these changes
Looks good, thanks!

2023-05-17 06:06 UTC, merged